apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls
spec:
  provider: azure
  secretObjects:                            # secretObjects defines the desired state of synced K8s secret objects
    - secretName: ingress-tls-csi
      type: kubernetes.io/tls
      data:
        - objectName: "aks-ingress-cert" #set the name of the object in KV
          key: tls.key
        - objectName: "aks-ingress-cert" #set the name of the object in KV
          key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "25f7aa57-5b02-466d-964a-afca588a743a" #$miKV_Client
    keyvaultName: "ankv221"                 # the name of the AKV instance $KV
    objects: |
      array:
        - |
          objectName: "aks-ingress-cert"
          objectType: secret
    tenantId: "081f9cb9-c6e1-4b1a-a2cd-a17b59c9f934"                    # the tenant ID of the AKV instance $tenantId